pipelines:
  pull-requests:
    '**':
      - step:
          name: Build, test and code inspection
          image: node:8-alpine
          caches:
            - node
          script:
            - npm install
            - npm run lint
            - npm run test

  branches:
    develop:
      - step:
          deployment: test
          name: Build, test, code inspection and deploy
          image: node:8-alpine
          caches:
            - node
          script:
            - npm install
            - npm run lint
            - npm run test
            - npm run deploy
    release/*:
      - step:
          deployment: staging
          name: Build, test, code inspection and deploy
          image: node:8-alpine
          caches:
            - node
          script:
            - npm install
            - npm run lint
            - npm run test
            - npm run deploy -- --stage staging
    master:
      - step:
          deployment: production
          name: Build, test, code inspection and deploy
          image: node:8-alpine
          caches:
            - node
          script:
            - npm install
            - npm run lint
            - npm run test
            - npm run deploy -- --stage prod
